name: fancricsport
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.1+2

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.2
  bot_toast: ^4.0.3
  connectivity_plus: ^2.3.9
  shared_preferences: ^2.0.5
  image_fade: ^0.6.2
  intl:
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.8
  google_mobile_ads: ^4.0.0
  facebook_audience_network: ^1.0.1
  flutter_fgbg: ^0.3.0
  badges: ^2.0.1
  in_app_review: ^2.0.8
  share_plus: ^7.2.2
  package_info_plus: ^5.0.1
  firebase_messaging:
  flutter_local_notifications:
  app_settings: ^5.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/image/


